import express from "express";
import path from "path";
import { createServer as createViteServer } from "vite";
import { GoogleGenAI } from "@google/genai";
import dotenv from "dotenv";

dotenv.config();

const app = express();
const PORT = 3000;

app.use(express.json());

// Lazy-initialized Gemini Client
let googleAI: any = null;
function getGoogleAI() {
  if (!googleAI) {
    const apiKey = process.env.GEMINI_API_KEY;
    if (!apiKey || apiKey === "MY_GEMINI_API_KEY") {
      console.log("Using local simulated responses because GEMINI_API_KEY is not configured.");
      return null;
    }
    googleAI = new GoogleGenAI({
      apiKey: apiKey,
      httpOptions: {
        headers: {
          'User-Agent': 'aistudio-build',
        }
      }
    });
  }
  return googleAI;
}

// API endpoint for study summarization and flashcards
app.post("/api/gemini/summarize", async (req, res) => {
  try {
    const { noteText, domain, university } = req.body;
    if (!noteText || noteText.trim() === "") {
      return res.status(400).json({ error: "No lecture notes or text provided." });
    }

    const ai = getGoogleAI();
    if (!ai) {
      // Return high-quality local template simulation as fallback
      const simulatedSummary = `### Simulated Lecture Summary (${domain || "General Study"})
*Here is a structured overview of your notes tailored for a student at ${university || "African University"}.*

1. **Core Concept Overview**: This lecture focuses on the primary components of **${domain || "General"} studies**, focusing on fundamental legal, cultural, or social frameworks relevant to the African continent.
2. **Key Definitions & Terminologies**:
   - *Key Term 1*: Primary element critical for exam prep.
   - *Key Term 2*: Auxiliary mechanism used to support central theories.
3. **High-Frequency Exam Focus**: 
   - Pay special attention to how these concepts are tested in typical Nigerian standard syllabi (e.g., continuous assessment (CA) focus).
   - Ensure clear distinction between classical and modern interpretations.

*This response is generated by the local simulator as the Gemini API Key is not set in Secrets.*`;

      const simulatedFlashcards = [
        { question: "What is the primary objective of this lecture subject?", answer: "To establish a baseline understanding of foundational concepts within a cultural and regulatory context." },
        { question: "Why is local context critical for this syllabus?", answer: "Because it adapts international frameworks to the specific socio-political structures of Nigeria/Africa." },
        { question: "What represents the typical Continuous Assessment weight for this course?", answer: "Usually 30% or 40% depending on departmental regulations, with the exam taking 60% or 70%." }
      ];

      return res.json({ summary: simulatedSummary, flashcards: simulatedFlashcards });
    }

    const promptText = `You are the ultimate digital study advisor on UniVerse, a university-focused academic and social platform for African and Nigerian students.
We need to summarize these lecture/study notes for a student, focusing on high-utility exam readiness, clear structures, and core terminologies.
Context:
- Subject Domain: ${domain || "General"}
- Student's University Context: ${university || "Nigerian/African university campuses"}

Please perform two tasks. Output your response as a valid JSON object with EXACTLY two fields:
"summary": a gorgeous markdown string presenting a structured, detailed study note summary containing definitions, core themes, and "Exam Pro-Tips" (referencing popular grading habits on Nigerian/African campuses where relevant).
"flashcards": an array of objects, where each object has "question": string, "answer": string. Generate exactly 3-4 high-yield flashcard questions.

Lecture notes to summarize:
${noteText}

Your output MUST be a strict, parsable JSON structure like:
{
  "summary": "### Title...",
  "flashcards": [ {"question": "...", "answer": "..."} ]
} Do not include markdown code block characters (\`\`\`json) or other text around the JSON, just the JSON string, so that it parses cleanly.`;

    const response = await ai.models.generateContent({
      model: "gemini-3.5-flash",
      contents: promptText,
    });

    const rawText = response.text || "";
    // Clean up typical markdown formatting wrapped if any
    let cleanedText = rawText.trim();
    if (cleanedText.startsWith("```json")) {
      cleanedText = cleanedText.substring(7);
    }
    if (cleanedText.startsWith("```")) {
      cleanedText = cleanedText.substring(3);
    }
    if (cleanedText.endsWith("```")) {
      cleanedText = cleanedText.substring(0, cleanedText.length - 3);
    }
    cleanedText = cleanedText.trim();

    try {
      const parsed = JSON.parse(cleanedText);
      res.json(parsed);
    } catch (parseError) {
      console.error("Failed to parse JSON response from Gemini:", rawText);
      // Fallback in case formatting was off but contains text
      res.json({
        summary: rawText,
        flashcards: [
          { question: "Key takeaway from the notes?", answer: "Review the generated summary details above for detailed concepts." }
        ]
      });
    }

  } catch (error: any) {
    console.error("Gemini Summarize API Error:", error);
    res.status(500).json({ error: error.message || "An error occurred during text generation." });
  }
});

// API endpoint for AI CGPA advice and grading forecast
app.post("/api/gemini/gpa-advisor", async (req, res) => {
  try {
    const { currentCGPA, targetCGPA, totalUnitsCurrent, baseScale, courses, university } = req.body;
    
    const semesterCourses = courses || [];
    const coursesStr = semesterCourses.map((c: any) => `- ${c.name} (${c.units} units): Current state: ${c.gradeState || "No grade yet"}`).join("\n");

    const ai = getGoogleAI();
    if (!ai) {
      // Simulated response
      const diff = parseFloat(targetCGPA) - parseFloat(currentCGPA);
      const direction = diff > 0 ? "climb" : "maintain";
      const targetMessage = diff > 0 
        ? `To boost your grade from **${currentCGPA}** to a target of **${targetCGPA}** on the ${baseScale} Scale, you need consistent performance.` 
        : `To sustain your strong position of **${currentCGPA}**, keep pushing in your main courses.`;

      const simulatedAdvice = `### CGPA Strategy Report (${university || "My Campus"})
${targetMessage}

#### 1. Semester Target GPA Goal
To hit your academic objective, you need to score a GPA of approximately **${Math.min(parseFloat(baseScale), parseFloat(targetCGPA) + 0.35).toFixed(2)}** in this active semester. 

#### 2. Key Course-by-Course Tactics
${semesterCourses.length === 0 ? "No active course inputs provided. Load standard courses to refine your predictions!" : semesterCourses.map((c: any) => {
  const unitsMultiplier = parseFloat(c.units) >= 3 ? "high-weight" : "medium-weight";
  return `- **${c.name}** (${c.units} Units): This is a **${unitsMultiplier}** course. Aim for a **Grade A or B** to avoid drag on your CGPA. Prioritize assignments and tests which consist of the core 30-40% continuous assessment.`;
}).join("\n")}

#### 3. Pro-Tips for ${university || "Nigerian Campuses"} (Simulated Advisory)
- **Continuous Assessment (CA) is King**: Do not slack in mid-semester assignments or tests. Many lecturers use them as a strict filter.
- **The Power of Units**: Focus double the efforts on 3 or 4 credit unit courses. Getting an 'A' in a 4-unit course cancels out a lower grade in a 1-unit or 2-unit course.
- **Past Questions (PQ)**: On many campuses, studying past questions is the ultimate hack. Locate papers from the last 5 years.

*This forecast was compiled by the UniVerse local mentor as no Gemini API Key was found in your settings.*`;

      return res.json({ advice: simulatedAdvice });
    }

    const advisorPrompt = `You are "UniVerse Mentor", an AI product architect and academic dean embedded in the UniVerse student platform. 
Provide a detailed, highly encouraging, strategic, and hyper-local plan to assist a student in meeting their CGPA target at ${university || "their campus"}.

Details of the student:
- Active University Scale: ${baseScale || "5.0"} Scale
- Current CGPA: ${currentCGPA}
- Target GP/CGPA Goal: ${targetCGPA}
- Current Accumulated Units: ${totalUnitsCurrent || "not specified"}
- Active Semester Courses:
${coursesStr}

Please review this information and output a comprehensive strategy (using standard Markdown format with rich spacing, lists, and bold keys) containing:
1. Academic Feasibility: Is their goal realistic? What GP do they need to hit in their active courses? Give the math.
2. High-Impact Courses: Highlight which of their active courses are high-weight (3 or 4 units) and how to handle them.
3. Nigerian/African Campus Survival Hacks: Give authentic, specific campus study tactics (mentioning strategies like CA prep, leverage/tackling 3-unit courses, getting study materials from departmental associations, and past questions (PQs)).
4. Ultimate Motivation sentence.

Keep it structured, insightful, and tailored for direct rendering.`;

    const response = await ai.models.generateContent({
      model: "gemini-3.5-flash",
      contents: advisorPrompt,
    });

    res.json({ advice: response.text || "Unable to formulate advice. Please try again." });

  } catch (error: any) {
    console.error("GPA Advisor API Error:", error);
    res.status(500).json({ error: error.message || "An error occurred during GPA forecasting." });
  }
});

// Serve static compiled UI or development server via Vite
async function startServer() {
  if (process.env.NODE_ENV !== "production") {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), "dist");
    app.use(express.static(distPath));
    app.get("*", (req, res) => {
      res.sendFile(path.join(distPath, "index.html"));
    });
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`UniVerse Server running on http://localhost:${PORT} in ${process.env.NODE_ENV || "development"} mode`);
  });
}

startServer();
